apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
labels:
  - pairs:
      platform.com/region: us-east-1
      platform.com/role: primary
    includeSelectors: false
patches:
  - path: patches/region-patch.yaml
    target:
      kind: ConfigMap
      name: platform-config