apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - deployment.yaml
labels:
  - pairs:
      app.kubernetes.io/managed-by: jarvis
      app.kubernetes.io/part-of: platform
    includeSelectors: false
namespace: platform-system